jobs:

###

  MFA-prod:
    name: ⚒ Dev-Deploy + restore PROD-DATA! to mfa.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { mfa.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit mfa'

  MFA-blank:
    name: ⚒ Dev-Deploy to mfa.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { mfa.ruby.zhdk.ch: true }
        environment_variables:
          USE_S3_BUILD_CACHE: 'true' # no further config == uses default, public cache instead of CI cache
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit mfa'

###

  NIMAAI-prod:
    name: ⚒ Dev-Deploy + restore PROD-DATA! to nimaai.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { nimaai.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit nimaai'

  NIMAAI-blank:
    name: ⚒ Dev-Deploy to nimaai.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { nimaai.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit nimaai'

###

  TOM-prod:
    name: ⚒ Dev-Deploy + restore PROD-DATA! to tom.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-with-prod-data.yml
    context:
      task_defaults:
        exclusive_global_resources: { tom.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit tom'

  TOM-blank:
    name: ⚒ Dev-Deploy to tom.ruby.zhdk.ch
    include: cider-ci/task-components/zhdk-dev-deploy-blank.yml
    context:
      task_defaults:
        exclusive_global_resources: { tom.ruby.zhdk.ch: true }
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'developer-hosts --limit tom'
