jobs:
  deploy-to-zhdk-leihs-staging-norestore:
    include: cider-ci/task-components/deploy-defaults.yml
    name: Deploy to zhdk-leihs-staging.ruby.zhdk.ch ***WITHOUT DB-RESTORE***

    context:
      task_defaults:
        exclusive_global_resources:
          "zhdk-leihs-staging.ruby.zhdk.ch": true
        environment_variables:
          DEPLOY_TARGET_INVENTORY: 'staging-hosts --limit zhdk-leihs-staging'

      tasks:
        deploy:
          include: cider-ci/task-components/zhdk-test-deploy.yml
          scripts:
            fetch-dump:
              body: echo SKIP
            restore-dump:
              body: echo SKIP
